[project]
name = "qutebrowser_profile"
readme = "README.md"
license = {file = "LICENSE"}
version = "0.1.0"
dependencies = ["attrs==22.2.0", "cattrs==23.1.2", "click==8.1.7", "colorama==0.4.6", "pyyaml==6.0.1"]

[project.scripts]
qt = "qutebrowser_profile:main"
